from os.path import expanduser, isfile

"""
Functions to handle the store-file (where tetris.py stores the maximum score).
"""

message = ("This file was generated by tetris.py. It keeps track of your "
           "max score in the Tetris game. For documentation, see"
           " http://www.johnloeber.com/docs/tetris.html.\n")

lenmsg = len(message)

def getmaxlines():
    """
    Retrieves the maximum score from the store-file.
    """
    try:
        with open(expanduser("~/.jtetris.txt"),"r") as f:
            return f.readlines()[1].rstrip('\n')
    except:
        return "0"

def writemaxlines(n):
    """
    Writes the maxmimum score to the store-file.
    """
    try:
        p = expanduser("~/.jtetris.txt")
        if not isfile(p):
            with open(p,"w") as f:
                f.write(message+str(n))
        else:
            with open(p,"r+") as f:
                f.seek(lenmsg)
                f.write(str(n))
    except:
        sys.stderr.write("Error: Not able to write to ~/.jtetris.txt.\n")
        return
